name: Build Chromium on EC2

on:
  workflow_dispatch: # Allow manual triggering

jobs:
  build-chromium:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - uses: actions/checkout@v4
      - name: Launch EC2 instance
        run: |
          # AMI: Ubuntu Server 22.04 LTS (HVM), SSD Volume Type
          # 32 vCPU, 64GB RAM, x86_64, 1'200 GB SSD, 10GiB Network, 1.376 USD/hour
          aws ec2 run-instances \
            --instance-type c5ad.8xlarge \
            --image-id ami-0884d2865dbe9de4b \
            --iam-instance-profile Name=chrxer \
            --instance-initiated-shutdown-behavior stop \
            --user-data file://build/build.sh \
            --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=ChromiumBuild},{Key=GIT_REPO,Value=$GITHUB_REPOSITORY},{Key=GIT_SHA,Value=$GITHUB_SHA}]' \
            --dry-run